### PR TITLE
feat: add api version to v3

### PR DESCRIPTION
**Pull request by AayushSaini101**
Resolve: #118

### CODE REVIEW

**Review by fmvilas — APPROVED** [review]
LGTM but I'm not a code owner. A part of me doesn't believe it's that easy 😄  I hope it is! It would be mean we did a great job 😄

**Comment by derberg** [comment]
@AayushSaini101 did you test this change? I mean after just changing the version, did you try to run code generation with such change? I would be surprised if that is enough to make template support v3

**Comment by dalelane** [comment]
I think more is needed than this. I've tried to make a start in moving this forward in https://github.com/asyncapi/java-template/pull/186 but I still don't think the work is complete even with that.

**Comment by dalelane** [comment]
closing in favour of https://github.com/asyncapi/java-template/pull/186

**Pull request closed without merging**
