### PR TITLE
feat: initial release

### PR DESCRIPTION
**Pull request by dan-r**
Time to release to NPM!

This reflects changes requested by @derberg in #3 and also concludes #2.

@lewis-relph as far as I can see we don't need these hooks anymore?

### CODE REVIEW

**Comment by derberg** [comment]
just for the context - this hook basically gives you this additional parameter https://github.com/asyncapi/java-template/blob/master/package.json#L66

it enables your template to work in the way that when someone generates your code, the asyncapi file used for generation will also end up in generated output and with this flag you can also decide where exactly.

so you either remove flag and dependencies and config, or just document the flag in the readme

**Comment by dan-r** [comment]
Thanks for the explanation @derberg. 
For this PR I think I'll go for the documentation approach!

**Review by lewis-relph — APPROVED** [review]
Looks good to me, glad we're keeping hooks. Bring on NPM! 👍

**Review by dalelane — APPROVED** [review]
lgtm

**Comment by derberg** [comment]
Congrats!!! https://twitter.com/AsyncAPISpec/status/1481256282103238660

**Pull request merged**
